!!org.myrobotlab.service.config.ArduinoConfig
attach:
- i01.leftHand.wrist
- i01.leftHand.ringFinger
- i01.left
- i01.leftHand.pinky
- i01.leftHand.majeure
- i01.leftHand.index
- i01.leftHand.thumb
connect: true
locale: null
name: i01.left
port: COM3
type: Arduino
