!!org.myrobotlab.service.config.ServoConfig
attach:
- i01.left
- i01.simulator
autoDisable: true
clip: true
enabled: false
idleTimeout: 3000
inverted: false
locale: null
maxIn: 25.0
maxOut: 25.0
minIn: 10.0
minOut: 10.0
name: i01.head.jaw
pin: '26'
rest: 10.0
speed: 100.0
sweepMax: null
sweepMin: null
type: Servo
