!!org.myrobotlab.service.config.RuntimeConfig
attach:
- i01
- i01.rightHand.index
locale: en-US
name: runtime
registry:
- runtime
- i01.mouth
- i01.mouth.audioFile
- i01
- i01.right
- i01.right.serial
- i01.ear
- i01.rightHand.index
- i01.chatBot
- i01.chatBot.search
- i01.htmlFilter
type: Runtime
