!!org.myrobotlab.service.config.ServoConfig
attach:
- i01.right
- i01.simulator
autoDisable: true
clip: true
enabled: false
idleTimeout: 3000
inverted: false
locale: null
maxIn: 90.0
maxOut: 90.0
minIn: 5.0
minOut: 5.0
name: i01.rightArm.bicep
pin: '8'
rest: 5.0
speed: 20.0
sweepMax: null
sweepMin: null
type: Servo
