!!org.myrobotlab.service.config.ServoConfig
attach:
- i01.left
- i01.simulator
autoDisable: true
clip: true
enabled: false
idleTimeout: 3000
inverted: false
locale: null
maxIn: 120.0
maxOut: 120.0
minIn: 60.0
minOut: 60.0
name: i01.torso.topStom
pin: '27'
rest: 90.0
speed: 5.0
sweepMax: null
sweepMin: null
type: Servo
