!!org.myrobotlab.service.config.AbstractSpeechSynthesisConfig
attach:
- i01.ear
- i01.mouthControl
blocking: false
locale: null
mute: false
name: i01.mouth
substitutions: null
type: MarySpeech
voice: Mark
