!!org.myrobotlab.service.config.ServoConfig
attach:
- i01.right
- i01.simulator
autoDisable: true
clip: true
enabled: false
idleTimeout: 3000
inverted: false
locale: null
maxIn: 180.0
maxOut: 180.0
minIn: 0.0
minOut: 0.0
name: i01.head.eyelidLeft
pin: '24'
rest: 0.0
speed: 50.0
sweepMax: null
sweepMin: null
type: Servo
