!!org.myrobotlab.service.config.ServoConfig
attach:
- i01.left
- i01.simulator
autoDisable: true
clip: true
enabled: false
idleTimeout: 3000
inverted: false
locale: null
maxIn: 180.0
maxOut: 180.0
minIn: 0.0
minOut: 0.0
name: i01.torso.lowStom
pin: '29'
rest: 90.0
speed: 5.0
sweepMax: null
sweepMin: null
type: Servo
